---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: codeserver-deploy
  namespace: codeserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codeserver
  template:
    metadata:
      labels:
        app: codeserver
    spec:
      volumes:
        - name: workspace-vol
          persistentVolumeClaim:
            claimName: codeserver-pvc
      containers:
        - name: codeserver-container
          image: linuxserver/code-server:amd64-4.95.3
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              valueFrom:
                configMapKeyRef:
                  name: codeserver-cm
                  key: TZ
            - name: DEFAULT_WORKSPACE
              valueFrom:
                configMapKeyRef:
                  name: codeserver-cm
                  key: DEFAULT_WORKSPACE
            - name: PROXY_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: codeserver-cm
                  key: PROXY_DOMAIN
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: codeserver-secret
                  key: PASSWORD
            - name: SUDO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: codeserver-secret
                  key: SUDO_PASSWORD
          volumeMounts:
            - name: workspace-vol
              mountPath: /config/workspace
          resources:
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 256Mi
          ports:
            - containerPort: 8443

---
apiVersion: v1
kind: Service
metadata:
  name: codeserver-svc
  namespace: codeserver
spec:
  type: ClusterIP
  selector:
    app: codeserver
  ports:
    - port: 8443
      targetPort: 8443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: codeserver-ingress
  namespace: codeserver
spec:
  ingressClassName: nginx
  rules:
    - host: code-163.47.8.144.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: codeserver-svc
                port:
                  number: 8443
