---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    name: bgg-app

spec:
  replicas: 4
  selector:
    matchLabels:
      name: bgg-app
  template:
    metadata:
      name: bggapp-deploy
      namespace: bggns
      labels:
        name: bgg-app

    spec:
      containers:
        - name: bggapp-container
          image: stackupiss/bgg-backend:v1
          imagePullPolicy: IfNotPresent
          env:
            - name: BGG_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: bggns-cm
                  key: db_user
            - name: BGG_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bggns-cm
                  key: db_host
            - name: BGG_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: bggns-secret
                  key: db_password
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    name: bgg-app
spec:
  type: ClusterIP
  selector:
    name: bgg-app
  ports:
    - name: web
      port: 8080
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bggapp-ing
  namespace: bggns
  labels:
    name: bgg-app
spec:
  ingressClassName: nginx
  rules:
    - host: bggns-163.47.8.144.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bggapp-svc
                port:
                  number: 3000
