---
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: minio-ns
  labels:
    app: minio
    name: minio-po
spec:
  clusterIP: None
  selector:
    app: minio
    name: minio-po
  ports:
    - name: data
      port: 9000
      targetPort: 9000
    - name: console
      port: 9090
      targetPort: 9090
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  namespace: minio-ns
spec:
  replicas: 4
  selector:
    matchLabels:
      app: minio
      name: minio-po
  serviceName: minio-hsvc
  volumeClaimTemplates:
    - metadata:
        name: data-vol
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: do-block-storage
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      name: minio-po
      labels:
        app: minio
        name: minio-po
    spec:
      securityContext:
        fsGroup: 1001
      containers:
        - name: minio-container
          image: bitnami/minio:2024.11.7
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: data-vol
              mountPath: /data
          envFrom:
            - configMapRef:
                name: minio-configmap
            - secretRef:
                name: minio-secret
          ports:
            - name: data
              containerPort: 9000
            - name: console
              containerPort: 9090
          resources:
            requests:
              cpu: 200m
              memory: 250Mi

---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio-ns
  labels:
    app: minio
    name: minio-po
spec:
  type: ClusterIP
  selector:
    app: minio
    name: minio-po
  ports:
    - name: data
      port: 9000
      targetPort: 9000
    - name: console
      port: 9090
      targetPort: 9090

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-data-ing
  namespace: minio-ns
  labels:
    app: minio
    name: minio-po
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "5"
spec:
  ingressClassName: nginx
  rules:
    - host: data.163.47.8.144.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-svc
                port:
                  number: 9000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-console-ing
  namespace: minio-ns
  labels:
    app: minio
    name: minio-po
spec:
  ingressClassName: nginx
  rules:
    - host: console.163.47.8.144.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: minio-svc
                port:
                  number: 9090
